#!/bin/sh
set +x

POST_ENVIRONMENT_SCRIPT=.singularity/post-environment
echo '# automatically generated by capture-environment.sh' > $POST_ENVIRONMENT_SCRIPT
echo export VERSION=$VERSION                   >> $POST_ENVIRONMENT_SCRIPT
echo export SQC_NONZERO_EXIT=$SQC_NONZERO_EXIT >> $POST_ENVIRONMENT_SCRIPT
